version: "3.6"

volumes:
  directus:
  directus-uploads:
  directus-cache:
  # meilisearch:
  # mariadb:
  # mongodb:

services:
  maria:
    image: mariadb:10.7.1-focal
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    # volumes:
    #   - mariadb:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_DATABASE=${MYSQL_SCHEMA}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    ports:
      - "${MEILISEARCH_PORT:-7700}:${MEILISEARCH_PORT:-7700}"
    # volumes:
    #   - meilisearch:/tmp/${APPNAME}/meilisearch
    environment:
      - "MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY}"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    # volumes:
    #   - mongodb:/data/db
    environment:
      - "MONGO_INITDB_DATABASE=${DATABASE_SCHEMA}"
      - "MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}"
  directus:
    image: directus/directus:latest
    ports:
      - "${CMS_PORT:-8055}:${CMS_PORT:-8055}"
    volumes:
      - directus-uploads:/directus/uploads
      - directus:/directus/extensions
      - directus:/directus/database
    environment:
      - "KEY=${DIRECTUS_KEY}"
      - "SECRET=${DIRECTUS_SECRET}"

      # - PUBLIC_URL=${CMS_HOST}
      # - HOST=${CMS_HOST}
      - PORT=${CMS_PORT}

      - "EMAIL_VERIFY_SETUP=true"
      - "EMAIL_FROM=${DIRECTUS_EMAIL_FROM}"
      - "EMAIL_TRANSPORT=${DIRECTUS_EMAIL_TRANSPORT}"
      - "EMAIL_SENDGRID_API_KEY=${SENDGRID_API_KEY}"

      - "DB_CLIENT=mysql"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_DATABASE=${MYSQL_SCHEMA}"
      - "DB_PORT=${MYSQL_PORT}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"

      - "DIRECTUS_STORAGE_LOCATIONS=s3,local"
      - "STORAGE_S3_DRIVER=s3"
      - "STORAGE_S3_ACL=FULL_CONTROL"
      - "STORAGE_S3_ROOT=${APPNAME}"
      - "STORAGE_S3_HEALTHCHECK_THRESHOLD=750"
      - "STORAGE_S3_ENDPOINT=${S3_ENDPOINT}"
      - "STORAGE_S3_REGION=${S3_REGION}"
      - "STORAGE_S3_BUCKET=${S3_BUCKET}"
      - "STORAGE_S3_KEY=${S3_ACCESS_KEY}"
      - "STORAGE_S3_SECRET=${S3_SECRET_KEY}"

      - "ADMIN_EMAIL=${DIRECTUS_ADMIN_EMAIL}"
      - "ADMIN_PASSWORD=${DIRECTUS_ADMIN_PASSWORD}"
